const weapons=[
 {name:'XM4',type:'Assault Rifle',tier:'S',desc:'Versatile all-rounder',stats:[34,68,81,74],attachments:'Monolithic Suppressor / Long Barrel',playstyle:'Aggressive flex'},
 {name:'Lachmann Sub',type:'SMG',tier:'S',desc:'Close-range shredder',stats:[42,42,88,58],attachments:'Bruen Pendulum / 40 Round Mag',playstyle:'Run & gun'},
 {name:'REM-7',type:'Sniper Rifle',tier:'S',desc:'One shot, one down',stats:[98,95,44,91],attachments:'Heavy Suppressor / Long Barrel',playstyle:'Anchor & pick'},
 {name:'HOG-20',type:'LMG',tier:'A',desc:'Heavy sustained fire',stats:[39,82,59,79],attachments:'Recoil Grip / 100 Round Belt',playstyle:'Hold power positions'},
 {name:'VOLT 9',type:'SMG',tier:'A',desc:'Close quarter menace',stats:[31,42,88,61],attachments:'Light Suppressor / Quickdraw',playstyle:'Flank & pressure'},
 {name:'Kilo 141',type:'Assault Rifle',tier:'A',desc:'Reliable laser beam',stats:[36,72,76,79],attachments:'Precision Stock / 60 Round Mag',playstyle:'Mid-range support'}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let favorites=JSON.parse(localStorage.getItem('wm-favorites')||'[]');
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('page-active',p.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#page-title').textContent=id.replace('-',' ').toUpperCase();if(id==='loadouts')renderLoadouts();if(id==='tier-list')renderTier();if(id==='compare')renderCompare();if(id==='favorites')renderFavorites();if(id==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-page]').forEach(el=>el.addEventListener('click',()=>showPage(el.dataset.page)));
$('.mobile-menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
function toggleFavorite(name,button){favorites=favorites.includes(name)?favorites.filter(x=>x!==name):[...favorites,name];localStorage.setItem('wm-favorites',JSON.stringify(favorites));button.classList.toggle('saved',favorites.includes(name));button.textContent=favorites.includes(name)?'★':'☆';if(favorites.includes(name)){let t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}}
$$('.favorite').forEach(b=>b.addEventListener('click',e=>toggleFavorite(e.currentTarget.closest('.weapon-card').querySelector('h3').textContent,e.currentTarget)));
function renderLoadouts(){let q=($('#loadout-search')?.value||'').toLowerCase(),type=$('#type-filter')?.value||'all';let list=weapons.filter(w=>(w.name.toLowerCase().includes(q)||w.desc.toLowerCase().includes(q))&&(type==='all'||w.type===type));$('#loadout-list').innerHTML=list.map(w=>`<article class="loadout-row"><div><h3>${w.name}</h3><small>${w.type.toUpperCase()} &bull; ${w.playstyle}</small></div><div class="row-stats">${w.stats.slice(0,3).map((s,i)=>`<span><i>${['DAMAGE','RANGE','CONTROL'][i]}</i>${s}</span>`).join('')}</div><div><small>CORE BUILD</small><strong>${w.attachments.split(' / ')[0]}</strong></div><button class="favorite ${favorites.includes(w.name)?'saved':''}" aria-label="Favorite">${favorites.includes(w.name)?'★':'☆'}</button></article>`).join('')||'<div class="empty-state"><h2>No intel found</h2><p>Try another weapon or category.</p></div>';$$('.loadout-row .favorite').forEach(b=>b.addEventListener('click',e=>toggleFavorite(e.currentTarget.closest('.loadout-row').querySelector('h3').textContent,e.currentTarget)))}
$('#loadout-search').addEventListener('input',renderLoadouts);$('#type-filter').addEventListener('change',renderLoadouts);
function renderTier(){let groups=['S','A','B','C'];$('#tier-board').innerHTML=groups.map(t=>`<div class="tier-row"><div class="tier-rank">${t}</div><div class="tier-weapons">${weapons.filter(w=>w.tier===t).map(w=>`<div class="tier-weapon">${w.name}<small>${w.type}</small></div>`).join('')||'<span style="color:#667">No ranked weapons</span>'}</div></div>`).join('')}
function renderCompare(){let a=weapons.find(w=>w.name===$('#compare-a').value),b=weapons.find(w=>w.name===$('#compare-b').value),labels=['DAMAGE','RANGE','MOBILITY','CONTROL'];$('#compare-board').innerHTML=[a,b].map(w=>`<div class="compare-col"><p class="eyebrow">${w.type}</p><h2>${w.name}</h2>${w.stats.map((s,i)=>`<div class="compare-stat"><span>${labels[i]}</span><div class="compare-bar"><i style="width:${s}%"></i></div><b>${s}</b></div>`).join('')}<p class="subtitle">${w.attachments}</p></div>`).join('')}
$('#compare-a').addEventListener('change',renderCompare);$('#compare-b').addEventListener('change',renderCompare);
function renderFavorites(){let saved=weapons.filter(w=>favorites.includes(w.name));$('#favorites .empty-state').style.display=saved.length?'none':'block';if(saved.length&&!$('#favorites .saved-list'))$('#favorites .page-intro').insertAdjacentHTML('afterend','<div class="loadout-list saved-list"></div>');let list=$('#favorites .saved-list');if(list)list.innerHTML=saved.map(w=>`<article class="loadout-row"><div><h3>${w.name}</h3><small>${w.type.toUpperCase()} &bull; ${w.playstyle}</small></div><div class="row-stats"><span><i>DAMAGE</i>${w.stats[0]}</span><span><i>RANGE</i>${w.stats[1]}</span><span><i>CONTROL</i>${w.stats[3]}</span></div><div><small>CORE BUILD</small><strong>${w.attachments.split(' / ')[0]}</strong></div><button class="favorite saved">★</button></article>`).join('')}
function renderProfile(){const count=$('#profile-favorite-count');if(count)count.textContent=favorites.length}
$$('.tier-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.tier-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
